version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: financetracker-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    container_name: financetracker-frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
