version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - financetracker-network

  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: financetracker
      POSTGRES_USER: financetracker
      POSTGRES_PASSWORD: random
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financetracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - financetracker-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: financetracker-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: financetracker
      DATABASE_USER: financetracker
      DATABASE_PASSWORD: random
      DATABASE_PORT: 5432
    networks:
      - financetracker-network

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-frontend
    container_name: financetracker-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=/api
    networks:
      - financetracker-network
  
networks:
  financetracker-network:
    driver: bridge
  
volumes:
  postgres_data:
  
